name: Droid Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: number

concurrency:
  group: droid-review-${{ github.event.pull_request.number || inputs.pr_number }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false

    steps:
      - name: Set PR number
        id: pr-number
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || steps.pr-details.outputs.head_sha }}

      - name: Check API keys
        env:
          FACTORY_API_KEY: ${{ secrets.FACTORY_API_KEY }}
          MODEL_API_KEY: ${{ secrets.MODEL_API_KEY }}
        run: |
          if [ -z "$FACTORY_API_KEY" ] || [ -z "$MODEL_API_KEY" ]; then
            echo "Missing API keys"
            exit 0
          fi

      - name: Install Droid CLI
        env:
          DROID_INSTALLER_SHA256: ${{ vars.DROID_INSTALLER_SHA256 }}
        run: |
          if [ ! -f "$HOME/.local/bin/droid" ]; then
            curl -fsSL https://app.factory.ai/cli -o droid-cli-installer.sh
            sh droid-cli-installer.sh
          fi
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Configure custom model
        env:
          MODEL_API_KEY: ${{ secrets.MODEL_API_KEY }}
        run: |
          mkdir -p "$HOME/.factory"
          cat > "$HOME/.factory/config.json" << 'EOF'
          {
            "custom_models": [
              {
                "model_display_name": "GLM-4.6 Coding Plan",
                "model": "GLM-4.6",
                "base_url": "https://api.z.ai/api/anthropic",
                "api_key": "MODEL_API_KEY_PLACEHOLDER",
                "provider": "zia"
              }
            ]
          }
          EOF
          jq --arg key "$MODEL_API_KEY" '.custom_models[0].api_key = $key' "$HOME/.factory/config.json" > "$HOME/.factory/config.json.tmp"
          mv "$HOME/.factory/config.json.tmp" "$HOME/.factory/config.json"

      - name: Test droid exec
        run: |
          echo "Testing droid exec with custom:GLM-4.6 model..."
          droid exec "hello world" --model custom:GLM-4.6 --skip-permissions-unsafe
